using VariableFrequencyOPF
using Test

import JuMP
import MathOptInterface

@testset "VariableFrequencyOPF.jl" begin
    include("opf.jl")

    try
        rm("results",force=true,recursive=true)
    catch IOError
        println("Unable to delete the results files generated by this test.")
    end
end
