name = "VariableFrequencyOPF"
uuid = "8ed6e67b-2f49-4d89-ba42-857abbbf04c3"
authors = ["David Sehloff"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
